{
 "title": "3D Printer",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Filament Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(extrusion_total[1y]))",
     "legendFormat": "One Year Filament"
    },
    {
     "expr": "sum(increase(extrusion_total[30d]))",
     "legendFormat": "30 Day Filament"
    }
   ]
  },
  {
   "title": "Extrusion",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "extrusion_print" }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature_bed_actual", "legendFormat": "Bed Actual" },
    { "expr": "temperature_bed_target", "legendFormat": "Bed Target" },
    { "expr": "temperature_tool0_actual", "legendFormat": "Hotend Actual" },
    { "expr": "temperature_tool0_target", "legendFormat": "Hotend Target" }
   ]
  },
  {
   "title": "Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "progress" },
    { "expr": "print_info", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Movement",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "movement_e", "legendFormat": "Extruder" },
    { "expr": "movement_z", "legendFormat": "Z-axis" }
   ]
  }
 ]
}