{
 "title": "3D Printer",
 "time": { "from": "2019-03-08T16:29:55.510Z", "to": "2019-03-09T02:47:34.862Z" },
 "panels": [
  {
   "title": "Filament Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(extrusion_total[1y]))",
     "legendFormat": "One Year Filament"
    },
    {
     "expr": "sum(increase(extrusion_total[30d]))",
     "legendFormat": "30 Day Filament"
    }
   ]
  },
  {
   "title": "Electricity Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time( (sum_over_time(current_power[1h])/1000/1000/count_over_time(current_power[1h]))[1y:5m] )/12",
     "legendFormat": "KwH One Year"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temperature_bed_actual", "legendFormat": "Bed Actual" },
    { "expr": "temperature_bed_target", "legendFormat": "Bed Target" },
    { "expr": "temperature_tool0_actual", "legendFormat": "Hotend Actual" },
    { "expr": "temperature_tool0_target", "legendFormat": "Hotend Target" }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "current_power/1000.0/1000.0", "legendFormat": "Watts" }
   ]
  },
  {
   "title": "Extrusion",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "extrusion_print" }
   ]
  },
  {
   "title": "Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "progress" },
    { "expr": "print_info", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Movement",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "movement_e", "legendFormat": "Extruder" },
    { "expr": "movement_z", "legendFormat": "Z-axis" }
   ]
  }
 ]
}