{
 "title": "BME Sensors",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Barom",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SensorBarom" }
   ]
  },
  {
   "title": "Humid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SensorHumid" }
   ]
  },
  {
   "title": "BME Sensors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "SensorTime*1000+0" },
    { "expr": "SensorHumid+0" },
    { "expr": "SensorBarom+0" },
    { "expr": "SensorTemp+0" },
    { "expr": "SensorSeq+0" }
   ]
  },
  {
   "title": "Sensor Sequence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SensorSeq" }
   ]
  }
 ]
}