{
 "title": "Power",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server UPS - Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upsHighPrecInputLineVoltage/10", "legendFormat": "vInput" },
    {
     "expr": "upsHighPrecInputMaxLineVoltage/10",
     "legendFormat": "vInputMax"
    },
    {
     "expr": "upsHighPrecInputMinLineVoltage/10",
     "legendFormat": "vInputMin"
    },
    { "expr": "upsHighPrecOutputVoltage/10", "legendFormat": "vOutput" }
   ]
  },
  {
   "title": "Server-Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "upsHighPrecOutputCurrent/10", "legendFormat": "current" },
    {}
   ]
  },
  {
   "title": "Server-Watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "upsHighPrecOutputVoltage*upsHighPrecOutputCurrent/100"
    }
   ]
  }
 ]
}