{
 "title": "Synology SNMP DashBoard",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "query_result(sum by (instance)(ifInOctets{job=\"synology\"}))"
   },
   {
    "name": "Interface",
    "query": "query_result(ifInOctets{job=\"synology\",instance=\"$Device\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic of $Interface Interfaces",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='synology',instance='$Device',ifName=~'$Interface'}[5m])  or irate(ifInOctets{job='synology',instance='$Device',ifName=~'$Interface'}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='synology',instance='$Device',ifName=~'$Interface'}[5m])  or irate(ifOutOctets{job='synology',instance='$Device',ifName=~'$Interface'}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "cpu temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "temperature" }
   ]
  },
  {
   "title": "systemFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "systemFanStatus" }
   ]
  },
  {
   "title": "cpuFanStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "cpuFanStatus" }
   ]
  },
  {
   "title": "systemStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "systemStatus" }
   ]
  },
  {
   "title": "powerStatus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "powerStatus" }
   ]
  },
  {
   "title": "raid-vol1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "raidStatus{raidName=\"0x566F6C756D652031\"}"
    }
   ]
  },
  {
   "title": "raid-vol2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "raidStatus{raidName=\"0x566F6C756D652032\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "laLoadInt/100" }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "diskTemperature" }
   ]
  },
  {
   "title": "disk temperature",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(diskTemperature)" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "100-ssCpuIdle" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1-((memAvailReal+memCached+memBuffer)/memTotalReal))*100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1-((memAvailReal+memCached+memBuffer)/memTotalReal))*100"
    }
   ]
  }
 ]
}