apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
spec:
  type: NodePort
  selector:
    app: "prometheus-wemo-exporter"
  ports:
    - port: 9801
      targetPort: 9801
      name: secure
      protocol: TCP
