dependencies:
- name: prometheus
  version: 8.8.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: grafana
  version: 2.0.2
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: prometheus-snmp-exporter
  version: 0.0.1
  repository: file://./prometheus-snmp-exporter
- name: prometheus-wemo-exporter
  version: 1.0.0
  repository: file://./prometheus-wemo-exporter
- name: prometheus-blackbox-exporter
  version: 4.1.1
  repository: https://kubernetes-charts.storage.googleapis.com/
