prometheus:
  alertmanager:
    persistentVolume:
      enabled: true
      storageClass: manual-prom-alertmanager
  server:
    persistentVolume:
      enabled: true
      storageClass: manual-prom
    service:
      type: NodePort
      nodePort: 31301
    enableAdminApi: true
  serverFiles:
    alerts: {}
    rules: {}

    prometheus.yml:
      rule_files:
        - /etc/config/rules
        - /etc/config/alerts

      scrape_configs:
        # envmon1
        - job_name: 'envmon1'
          metrics_path: /metrics
          scrape_interval: 10s
          static_configs:
            - targets:
              - 198.0.0.247:8000

        - job_name: 'envmon2'
          metrics_path: /metrics
          scrape_interval: 10s
          static_configs:
            - targets:
              - 198.0.0.249:8000

        # 3dprinter
        - job_name: '3dprinter'
          metrics_path: /metrics
          scrape_interval: 10s
          static_configs:
            - targets:
              - 198.0.0.246:8000

        - job_name: 'ups_server'
          static_configs:
            - targets:
              - 198.0.0.189
          metrics_path: /snmp
          params:
            module: [smbaker_apcups]
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: promgraf-prometheus-snmp-exporter:9116

grafana:
  adminUser: admin
  adminPassword: myadminpassword
  service:
    type: NodePort
    nodePort: 31300
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://promgraf-prometheus-server.default.svc.cluster.local
          access: proxy
          isDefault: true

prometheus-snmp-exporter:
  config: "bogus"
  service:
    type: NodePort
